version: "3.9"

services:
  api:
    container_name: go-rest-template
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - APP_PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=go_rest
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: postgres-db-go-rest-template
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_rest
    ports:
      - "54390:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
